<aside class="right-side">
    <section class="content-header">
        <h1>Company</h1>
        <ol class="breadcrumb">
            <li>
                <a href="#"><i class="fa fa-dashboard"></i> Home</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller'=>'company','action'=>'index'),null,true)?>"> Company</a>
            </li>
            <li>
                Edit Company
            </li>
        </ol>
    </section>    
    <section class="content">
        <div class="col-xs-12 pad rightalign">
            <button class="btn btn-primary" onclick="location.href='<?php echo $this->url(array('controller'=>'company','action'=>'index'),null,true) ?>'">List Company</button>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <?php if(count($this->messages) > 0): ?>
                        <div class="message">
                            <?php foreach ($this->messages as $message) { ?>
                                <?php echo '<div class="bg-' . key($message) . ' with-padding block-inner">' . current($message) . '</div>'; ?>
                            <?php } ?>
                        </div>
                    <?php endif; ?>
                    <?php if(isset($this->error)):  ?>
                        <div class="message">
                            <?php foreach($this->error as $key=>$error): ?>
                                <div class="bg-danger with-padding centeralign" style="text-align: left">
                                    <?php echo $error;?>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <div class="box-header">
                        <h3 class="box-title">Edit Company</h3>
                    </div>
                    <form role="form" method="post" name="addCompanyForm" action="<?php echo $this->url(array('controller'=>'company','action'=>'edit'))?>" class="validate">
                        <?php if(isset($this->companyData['id'])): ?>
                            <input type="hidden" name="id" value="<?php echo $this->companyData['id']?>" />
                        <?php endif; ?>                        
                        <div class="box-body">
                            <div class="form-group">
                                <label for="companyName">Name</label>
                                <input type="text" placeholder="Enter Name" name="companyName" id="companyName" class="form-control required" value="<?php echo $this->companyData['company_name']?>">
                            </div>
                            <div class="form-group">
                                <label for="name">Address</label>
                                <input type="text" placeholder="Enter Address" name="address1" id="address1" class="form-control required" value="<?php echo $this->companyData['address_1']?>">
                                <div class="pad"></div>
                                <input type="text" name="address2" id="address2" class="form-control" value="<?php echo $this->companyData['address_2']?>">
                            </div>
                            <div class="form-group">
                                <label for="city">City</label>
                                <input type="text" placeholder="Enter City" name="city" id="city" class="form-control required" value="<?php echo $this->companyData['city']?>">
                            </div>
                            <div class="form-group">
                                <label for="state">State</label>
                                <input type="text" placeholder="Enter State" id="state" name="state" class="form-control required" value="<?php echo $this->companyData['state']?>">
                            </div>
                            <div class="form-group">
                                <label for="zipcode">Zipcode</label>
                                <input type="text" placeholder="Enter Zipcode" name="zipcode" id="zipcode" class="form-control required" value="<?php echo $this->companyData['zipcode']?>">
                            </div>
                            <div class="form-group">
                                <label for="phone1">Phone No</label>
                                <input type="text" placeholder="Enter Phone No" name="phone1" id="phone1" class="form-control required" value="<?php echo $this->companyData['phone_1']?>">
                            </div>
                            <div class="form-group">
                                <label for="phone2">Alt. Phone No</label>
                                <input type="text" placeholder="Enter Alternate Phone No" name="phone2" id="phone2" class="form-control" value="<?php echo $this->companyData['phone_2']?>">
                            </div>
                            <div class="form-group">
                                <label for="status">Status</label>
                                <select class="form-control required" name="status" id="status">
                                    <option value=""> Please Select </option>
                                    <option value="1" <?php if(1 == $this->companyData['status']): ?> selected="selected" <?php endif; ?>>Active</option>
                                    <option value="0" <?php if(0 == $this->companyData['status']): ?> selected="selected" <?php endif; ?>>In Active</option>
                                </select>
                            </div>
                        </div>
                        <div class="box-footer rightalign">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>                
            </div>
        </div>
    </section>
</aside>