<aside class="right-side">
    <section class="content-header">
        <h1>Users</h1>
        <ol class="breadcrumb">
            <li>
                <a href="#"><i class="fa fa-dashboard"></i> Home</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'users', 'action' => 'index'), null, true) ?>"> Users</a>
            </li>
            <li>
                Add User
            </li>
        </ol>
    </section>    
    <section class="content">
        <div class="col-xs-12 pad rightalign">
            <button class="btn btn-primary" onclick="location.href = '<?php echo $this->url(array('controller' => 'users', 'action' => 'index'), null, true) ?>'">List User</button>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <?php if (count($this->messages) > 0): ?>
                    <div class="message">
                        <?php foreach ($this->messages as $message) { ?>
                            <?php echo '<div class="bg-' . key($message) . ' with-padding block-inner">' . current($message) . '</div>'; ?>
                        <?php } ?>
                    </div>
                <?php endif; ?>
                <?php if (isset($this->error)): ?>
                    <div class="message">
                        <?php foreach ($this->error as $key => $error): ?>
                            <div class="bg-danger with-padding centeralign" style="text-align: left">
                                <?php echo $error; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Add User</h3>
                    </div>
                    <form role="form" method="post" name="addUserForm" action="<?php echo $this->url(array('controller' => 'users', 'action' => 'add'), null, true) ?>" class="validate" enctype="multipart/form-data">
                        <?php if (isset($this->userData['id'])): ?>
                            <input type="hidden" name="id" value="<?php echo $this->userData['id'] ?>" />
                        <?php endif; ?>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label for="company">Company</label>
                                        <select class="form-control required" name="company" id="company">
                                            <option value=""> Please Select </option>
                                            <?php foreach ($this->companyData as $company): ?>                                    
                                                <option value="<?php echo $company['id'] ?>" <?php if ($company['id'] == $this->userData['company_id']): ?> selected="selected" <?php endif; ?>><?php echo $company['company_name'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="name">First Name</label>
                                        <input type="text" placeholder="Enter Name" name="firstname" id="firstname" class="form-control required" value="<?php echo $this->userData['firstname'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Last Name</label>
                                        <input type="text" placeholder="Enter Name" name="lastname" id="lastname" class="form-control required" value="<?php echo $this->userData['lastname'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="username">Username</label>
                                        <input type="text" placeholder="Enter Username" name="username" id="username" class="form-control required" value="<?php echo $this->userData['username'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="username">Email</label>
                                        <input type="email" placeholder="Enter Email" id="email" name="userEmail" class="form-control required" value="<?php echo $this->userData['email'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="password" placeholder="Password" name="password" id="password" class="form-control required">
                                    </div>
                                    <div class="form-group">
                                        <label for="role">Role</label>
                                        <select class="form-control required" name="role" id="role">
                                            <option value=""> Please Select </option>
                                            <?php foreach ($this->roleData as $role): ?>                                    
                                                <option value="<?php echo $role['id'] ?>" <?php if ($role['id'] == $this->userData['role_id']): ?> selected="selected" <?php endif; ?>><?php echo $role['role_name'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="status">Status</label>
                                        <select class="form-control required" name="status" id="status">
                                            <option value=""> Please Select </option>
                                            <option value="1" <?php if (1 == $this->userData['status']): ?> selected="selected" <?php endif; ?>>Active</option>
                                            <option value="0" <?php if (0 == $this->userData['status']): ?> selected="selected" <?php endif; ?>>In Active</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label for="address1">First Address</label>
                                        <input type="text" placeholder="Enter Address" name="address1" id="address1" class="form-control required" value="<?php echo $this->userDetailsData['address_1'] ?>">
                                        <div class="pad"></div>
                                        <input type="text" name="address2" id="address2" class="form-control" value="<?php echo $this->userDetailsData['address_2'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="city">City</label>
                                        <input type="text" placeholder="Enter City" name="city" id="city" class="form-control required" value="<?php echo $this->userDetailsData['city'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="state">State</label>
                                        <input type="text" placeholder="Enter State" name="state" id="state" class="form-control required" value="<?php echo $this->userDetailsData['state'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="zipcode">Zipcode</label>
                                        <input type="text" placeholder="Enter Zipcode" id="zipcode" name="zipcode" class="form-control required" value="<?php echo $this->userDetailsData['zipcode'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="phone1">Phone No.</label>
                                        <input type="text" placeholder="Enter Phone No" name="phone1" id="phone1" class="form-control required" value="<?php echo $this->userDetailsData['phone_1'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="phone2">Alt. Phone No.</label>
                                        <input type="text" placeholder="Enter Alternate Phone No" name="phone2" id="phone2" class="form-control" value="<?php echo $this->userDetailsData['phone_2'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="profileImage">Image</label>
                                        <input type="file" name="profileImage" id="profileImage" >
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer rightalign">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>    
            </div>
        </div>
    </section>
</aside>