<div class="form-box" id="login-box">
    <div class="header">Sign In</div>
    <form action="<?php echo $this->url(array('controller' => 'users', 'action' => 'login')) ?>" method="post" class="validate">
        <div class="body bg-gray">
            <?php if(isset($this->error)) { ?>
            <div class="alert alert-danger alert-dismissable" style="margin-left: 0px;">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                <?php echo $this->error; ?>
            </div>
            <?php } ?>
            <div class="form-group">
                <input type="text" name="email" class="form-control required" placeholder="Email or Username"/>
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form-control required" placeholder="Password"/>
            </div>          
            <div class="form-group">
                <input type="checkbox" name="remember_me"/> Remember me
            </div>
        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block">Sign me in</button>  
            <p><a href="#">I forgot my password</a></p>            
        </div>
    </form>
</div>