<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm no-margin pull-right">
        <?php if (isset($this->previous)): ?>
            <li>
                <a href="<?php echo $this->url(array('controller' => Zend_Controller_Front::getInstance()->getRequest()->getControllerName(),'action' => Zend_Controller_Front::getInstance()->getRequest()->getActionName(),'page' => $this->first)); ?>">First</a>
            </li>
        <?php else: ?>
            <!--<li>First</li>-->
        <?php endif; ?>
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li>
                    <a href="<?php echo $this->url(array(
                                            'controller' => Zend_Controller_Front::getInstance()->getRequest()->getControllerName(), 
                                            'action' => Zend_Controller_Front::getInstance()->getRequest()->getActionName(), 
                                            'page' => $page
                                        )
                                   );
                              ?>">
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li ><a href="javascript:void(0)"><?php echo $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if (isset($this->next)): ?>
            <li><a href="<?php echo $this->url(array('controller' => Zend_Controller_Front::getInstance()->getRequest()->getControllerName(), 
                                            'action' => Zend_Controller_Front::getInstance()->getRequest()->getActionName(),'page' => $this->last)); ?>">Last</a></li>
        <?php else: ?>
            <!--<li>Last</li>-->
        <?php endif; ?>
    </ul>
<?php endif; ?>